### PR TITLE
initial AIX support for node-oracledb

### PR DESCRIPTION
**Pull request by schmafu**
Signed-off-by: Hannes Prirschl <hannes.prirschl@me.com>

### CODE REVIEW

**Comment by cjbj** [comment]
@schmafu thank you.  Did you submit the OCA paperwork? https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md

**Comment by schmafu** [comment]
Yes, I mailed it one hour ago but I didn't get a response yet.

**Comment by cjbj** [comment]
@schmafu it will take a day or two; they do them in batches.

**Comment by cjbj** [comment]
Whoops

**Comment by cjbj** [comment]
Thank you!

**Comment by cjbj** [comment]
@schmafu in the next drop of code I will change the default base path in the AIX build from /opt/oracle/instantclient_12_1 to /opt/oracle/instantclient to match all the other platforms.

**Pull request merged**
