### PR TITLE
Added index.d.ts to expose types for typescript.

### PR DESCRIPTION
**Pull request by Bigous**
Resolving issue #169.

### CODE REVIEW

**Comment by Bigous** [comment]
Hi @cjbj, I think we could cancel this pull request until we decide if we are going to keep DefinelyTyped or use typescript as a helper at JavaScript layer, so we can have this automagicaly generated (and so the api documentation).
What do you think?
[]'s

**Comment by Bigous** [comment]
Just to attach things - we discussed it, ending in lets wait at #333.
From that point to now (7 months), Typescript evolved a lot. I really thin that it would be very nice to have the Javascript part rewritten in TypeScript generating the Javascript and adding definitions and documentation on it.

**Comment by cjbj** [comment]
@Bigous thanks for the updated pull at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10323   I think that is the right home for the definition file at the moment.  You may recall I had some reservations about merging to node-oracledb and there are a bunch of other things (temporary lobs, longs etc) that need attention.  If you close this, we can alweays reopen it later.

**Comment by Bigous** [comment]
Sure, lets keep it separated for now and reopen later or create another one !!!

**Pull request closed without merging**
