### PR TITLE
adds support for pre-compiled binaries

### PR DESCRIPTION
**Pull request by bchr02**
### Using node-pre-gyp and a new bin folder, this pull request adds:

1. **The ability for node-oracledb developers to package binaries, or automate the process of packaging binaries, by performing (or scripting) the following tasks in the following order.**
  1. Install C++ build environment as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  2. Install Node.js as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  3. Install Python 2.7 as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  4. Install the free Oracle Instant Client ZIPs as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  5. ```set ORACLE_HOME=C:\oracle\instantclient``` for Linux use ```export``` instead of ```set```
  6. ```set PATH=%ORACLE_HOME%;%PATH%``` for Linux use ```export``` instead of ```set```
  7. ```set OCI_LIB_DIR=%ORACLE_HOME%\sdk\lib\msvc``` for Linux use ```export``` instead of ```set```
  8. ```set OCI_INC_DIR=%ORACLE_HOME%\sdk\include``` for Linux use ```export``` instead of ```set```
  9. git clone https://github.com/oracle/node-oracledb *or while testing with my repo use https://github.com/bchr02/node-oracledb#1.5.0*
  10. cd node-oracledb
  11. ```npm install nan```
  12. ```npm install node-gyp -g```
  13. ```npm install node-pre-gyp -g```
  14. ```node-pre-gyp clean```
  15. ```node-pre-gyp configure```
  16. ```node-pre-gyp build```
  17. ```node-pre-gyp package```
  18. ```xcopy build\stage\*.* bin /C /Y``` or for Linux: ```cp -f build/stage/* bin```

2. **The ability for node-oracledb to be installed without the need for a build environment. The following would be a revised list of steps to install node-oracledb once we start including the binaries in the bin folder and a compatible system is used.**
  1. Install Node.js as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  2. Install the free Oracle Instant Client ZIPs as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
  4. ```set ORACLE_HOME=C:\oracle\instantclient``` for Linux use ```export``` instead of ```set```
  5. ```set PATH=%ORACLE_HOME%;%PATH%``` for Linux use ```export``` instead of ```set```
  6. ```set OCI_LIB_DIR=%ORACLE_HOME%\sdk\lib\msvc``` for Linux use ```export``` instead of ```set```
  7. ```set OCI_INC_DIR=%ORACLE_HOME%\sdk\include``` for Linux use ```export``` instead of ```set```
  8. binary is found in node-oracledb's bin folder.

3. **The ability for a node-oracledb install to fall back to building when a binary is not found.**
  1. A build environment would be needed otherwise the install would fail.

**IMPORTANT TO UNDERSTAND:** The bin folder is an online only folder. When npm installing node-oracledb the bin folder will not downloaded. Instead, node-pre-gyp will check the **online** github folder for a suitable file. ***Therefore, while testing and locally compiling be sure to remember this and not try to install from a git cloned copy of node-oracledb that you have compiled for.***

*By the way, you're going to want to reject any of the files within the bin folder and also within package.json change the binary.host path so ```bchr02``` is changed to ```oracle```*
 
cc: https://github.com/oracle/node-oracledb/issues/18

Signed-off-by: Bill Christo <billchristo@gmail.com>

### CODE REVIEW

**Comment by cjbj** [comment]
Thanks @bchr02

**Comment by slfletch** [comment]
Is this pulll request going to be merged into the master?  I had thought that OCA accepted would mean yes but wanted to verify.

**Comment by bchr02** [comment]
I will be resubmitting this pull request once I fix my fork later today. I have another update to push upstream but was unable to because I was making changes to the master branch instead of another...

**Comment by bchr02** [comment]
resubmitted here: https://github.com/oracle/node-oracledb/pull/392

**Comment by slfletch** [comment]
Thank you!

**Comment by cjbj** [comment]
@slfletch because the tooling and licenses need to be reviewed (out of my control!) the PR may take some time to get merged.

**Pull request closed without merging**
