### PR TITLE
Keep method name after wrapping

### PR DESCRIPTION
**Pull request by sla100**
```js
import oracledb from 'oracledb';
console.log( oracledb.getConnection );

// currently - [Function: bound ]
// after patch - [Function: bound getConnection]
```

```
Signed-off-by: Sławomir Osoba <sla100@poczta.fm>
```

### CODE REVIEW

**Comment by cjbj** [comment]
@sla100 It's great to see some handy PRs.   I'd love to get these in our next release, which we are wrapping up.  Can you point me at your entry in https://oca.opensource.oracle.com/?ojr=contrib-list or fill in its "paperwork", see https://oca.opensource.oracle.com/?ojr=faq ?  Also do you happen to have some tests, particularly for the error stack PR?

**Comment by sla100** [comment]
Of course. I sent my application to OCA. I also added a test file in the second PR.

**Comment by cjbj** [comment]
@sla100 Thanks for submitting the OCA.  Can you ping me when it gets accepted?

**Comment by sla100** [comment]
> @sla100 Thanks for submitting the OCA. Can you ping me when it gets accepted?

You're welcome. But doesn't it require your interaction?

Q&A:
> I submitted the OCA – what is next? How can I find out if it was accepted?
> Contact the project maintainers (e.g., through comments on your GitHub PR, Slack channels, or mailing lists).

**Comment by cjbj** [comment]
> But doesn't it require your interaction?

Not that they've told me.   I would have thought they emailed you - like used to happen when the process was more manual.  
If you don't hear soon, let me know and I'll chase up internally.  Did you use the same email address as in the signed-off message?  If so, I don't see you in the system yet.

**Comment by cjbj** [comment]
This got merged as https://github.com/oracle/node-oracledb/commit/31994984421554f1863801f301be749421da72aa
Good work and thanks for contributing!

**Pull request closed without merging**
