### PR TITLE
Build with NaN

### PR DESCRIPTION
**Pull request by Bigous**
Hi people,

This pull intend to solve issue #2 .

After some headaches, I could compile and run this driver wrapper with the NaN on IOJS 1.5.0 x64 on Windows.

I've tested only select commands and I need help to test everything, but it's usable.

We need some automated tests to see if all of this is working properly.

People who wanna run on IOJS on Windows, must run with iojs.exe and not node.exe due to a bug in iojs.

Hope have helped.
tks.
Richard

### CODE REVIEW

**Comment by cjbj** [comment]
Fantastic! It would be great if you can sign the OCA (see CONTRIBUTING.md) so we can merge this.
Releasing a test suite is still backed up for non technical reasons out of my control.

**Comment by Bigous** [comment]
Hi @cjbj 

I've sent it a cuple of minutes ago.

Tks for your fast reply! ;)

**Comment by alexsantos** [comment]
Just compiled it on a OL6.6 x86_64 and it worked. Just some warnings on the examples.
```
[node@nodeserver oracle]$ iojs webapp.js 
sys is deprecated. Use util instead.
util.puts: Use console.log instead
```

**Comment by Bigous** [comment]
Hi @alexsantos ,

The warning was in the examples and not in the driver wrapper itself.

I removed the sys dependency from webapp.js, just to be clean ;)

Tks for your help.

**Comment by alexsantos** [comment]
:+1:

**Comment by Bigous** [comment]
I have merged the latest commits to this pull so it can flawlessly be merged. 
Please, consider to merge it soon so we could avoid merge issues.

**Comment by lebolo** [comment]
:+1:

**Comment by alexsantos** [comment]
:+1:

**Comment by cjbj** [comment]
Hi @Bigous any merge will be some time off since the devs are busy continuing the other features (and projects) that they had already started and will need time to evaluate your patch.  I was told your OCA form should be being processed this week. There are also some other administrative things pending, too.   I'll let you know the progress.

**Comment by cjbj** [comment]
@Bigous can you add the signoff on your commit? See https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md

**Comment by pkoretic** [comment]
:+1: 
tested this on Ubuntu 14.10 with node 0.10, 0.12 and on Arch Linux with iojs 1.6.1.
It all works as expected in our tests

It would be nice to have it merged soon @Bigous @cjbj  :)

**Comment by Bigous** [comment]
Hi @cjbj, I have had signed it already (2 weeks ago).

I received the e-mail from dalibor.topic@oracle.com (2 days ago) confirming that the OCA was ok. Could you contact them to see if I missed something and / or guide me in what could I have missed?

**Comment by Bigous** [comment]
Thanks @pkoretic.

Testing it on many platforms and with all major versions on both NodeJS and IOJS was awesome!

**Comment by bchr02** [comment]
@Bigous I think what @cjbj is asking for is this:
>For pull requests to be accepted into node-oracledb, the bottom of your commit message must have the following line using your name and e-mail address as it appears in the OCA Signatories list.

>Signed-off-by: Your Name <you@example.org>

**Comment by Bigous** [comment]
Ok, if it was about of this, I had some commits with the signoff.
I've bumped a commit just to add the signoff on the lastone... @cjbj please see if it is good to go.

**Comment by Bigous** [comment]
Ok, Finally I've got how to signoff previous commits.
@cjbj Some commits are with 2 signoffs because it was commited with signoff.
As a curiosity and documentation, the command that I used was:
```shell
git filter-branch --msg-filter "cat - && echo && echo 'Signed-off-by: Richard Natal <bigous@gmail.com>'" -- --author=Bigous HEAD
```
And then I pushed it with force option to rewrite the previous commits.
```shell
git push -f
```
If someone has cloned my fork, please, clone it again, so it can be synced.

**Comment by cjbj** [comment]
Thanks @Bigous - that was the signoff I needed from your side.  Now we are just waiting some internal reviews and then we will be able to look at merging & testing.

**Comment by cjbj** [comment]
@pkoretic thanks for the tests!

**Comment by Bigous** [comment]
@cjbj Merged to be easier to acept the pull.

**Comment by pkoretic** [comment]
@cjbj any news on this one? :)

**Comment by cjbj** [comment]
@pkoretic our internal approval process is progressing, but is not complete.  I think the biggest hurdles have been jumped (famous last words!)

**Comment by Bigous** [comment]
Hi @cjbj ,
Any news on this one?

**Comment by cjbj** [comment]
@Bigous approvals are still pending.  I did some door knocking today to help nudge the issue along.

**Comment by Bigous** [comment]
Ok, tks Chris

**Comment by hertzg** [comment]
Abby updates?

**Comment by cjbj** [comment]
@hertzg waiting on just one final approval.

**Comment by hertzg** [comment]
@cjbj Great! thx for update

**Comment by Bigous** [comment]
@cjbj , I'm merging my fork with version 0.5 and got some warnings. almost all of them because DPI_SZ_TYPE to unsigned long when calling GetOutBinArray with executeBaton->rowsAffected...
I'll post my merge, but it could be a problem (in original code).

**Comment by cjbj** [comment]
@Bigous I'll pass that on.  Sorry we are still in a holding-pattern on official NAN support.

**Comment by fuson** [comment]
@Bigous, i can't build your fork with this PR on Mac OS X:

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
../src/njs/src/njsConnection.cpp:1254:49: error: conditional expression is ambiguous; 'Local<v8::Primitive>' can be converted to
      'Local<v8::String>' and vice versa
                    ( binds->ind[index] == -1 ) ? NanNull() :
                                                ^ ~~~~~~~~~
../src/njs/src/njsConnection.cpp:1261:48: error: conditional expression is ambiguous; 'Local<v8::Primitive>' can be converted to
      'Local<v8::Integer>' and vice versa
                    (binds->ind[index] == -1 ) ? NanNull() :
                                               ^ ~~~~~~~~~
../src/njs/src/njsConnection.cpp:1266:48: error: conditional expression is ambiguous; 'Local<v8::Primitive>' can be converted to
      'Local<v8::Number>' and vice versa
                    (binds->ind[index] == -1 ) ? NanNull() :
                                               ^ ~~~~~~~~~

**Comment by Bigous** [comment]
Hi @fuson, I have been trying to keep the code as close to the original as possible, but, to solve this ambiguity, I had to change a little bit the code to avoid operator ?: together with NanNull().

I dont have a Mac to teste. Coult you see if it works for you?

tks.

**Comment by cjbj** [comment]
Yay!  Thanks @Bigous.  There are still a few compile warnings on some versions of Linux we'll look at.

**Comment by hertzg** [comment]
Thanks @Bigous & @cjbj

**Comment by cjbj** [comment]
@hertzg All credit is to @Bigous 

@richlim I'm tagging you here since you explicitly mentioned NAN in https://github.com/oracle/node-oracledb/issues/85. I hope you will be able to contribute to node-oracledb.

**Comment by Bigous** [comment]
Hi @cjbj Thanks - you had a lot of effort to merge this one ;) almost a novel!

**Pull request merged**
