### PR TITLE
Support downloading binary package using external application.

### PR DESCRIPTION
**Pull request by bmocm**
The need to download binaries from github as part of the node-oracledb install is problematic for users behind proxies.  While there is limited support for proxies the installer will not be able to handle complex cases given the goal of not introducing additional dependencies.  For example our workplace uses a proxy that requires authentication using SPNEGO/GSSAPI.  I propose allowing the user to specify an external application to use to download the binaries.

### CODE REVIEW

**Comment by cjbj** [comment]
Improvements to installation are very welcome!

Have you signed the https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md (is the template clear enough on this)?  The OCA is a prerequisite for PRs to be accepted.  Submitting code without signing the OCA can be problematic for us to ever make changes in related areas.

Regarding this PR, it raise some questions about any potential security risks, since it opens up the possibility of silent injection of binaries from a different source.  This requires some thought in the context of the whole open source space, with unsigned binaries etc.

**Comment by bmocm** [comment]
I e-mailed in a signed OCA prior to submitting this PR so I imagine it has not been processed yet.  Agree about the potential security issue.  My thinking was that by using an environment variable to point to the executable it is at the discretion of the user running the install and needs to be explicitly set.

**Comment by dmcghan** [comment]
@bmocm 

> The need to download binaries from github as part of the node-oracledb install is problematic for users behind proxies.

This isn't required, it's only done for convenience. Are you able to pull in the source from NPM and compile it after?

**Comment by dmcghan** [comment]
Have you tried `npm install oracle/node-oracledb#v3.0.1`?

**Comment by bmocm** [comment]
npm install oracle/node-oracledb#v3.0.1

> oracledb@3.0.1 install /app/node_modules/oracledb
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
gyp ERR! stack     at ClientRequest.onConnect (/usr/lib/node_modules/npm/node_modules/tunnel-agent/index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:273:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:474:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:219:10)
gyp ERR! stack     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/oracledb
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-20T14_30_52_562Z-debug.log

**Comment by cjbj** [comment]
@bmocm Do you need any special setup in your network for npm to access github.com the way I assume it was able to access npm.com? Try with the install `--verbose` option to get more info about what npm is doing. And/or try `npm install https://github.com/oracle/node-oracledb/releases/download/v3.0.1/oracledb-src-3.0.1.tgz`, though I expect the outcome will be the same.

Both will download source for compilation, so they are not as easy as using a pre-built binary. 

I heard your OCA needs re-submission.  I doubt I'll get any security discussion done before the US Thanksgiving, and maybe not for some time after that (due to a general backlog in the group I want to discuss it with).

**Comment by cjbj** [comment]
@bmocm here are some other thoughts: what about [hosting your own packages](https://oracle.github.io/node-oracledb/INSTALL.html#selfhost), or a simpler PR like https://github.com/oracle/node-oracledb/pull/944 to host your own binaries?

**Comment by bmocm** [comment]
Happy Thanksgiving!  Verbose log below.  Nothing new, the 407 error is from our SPNEGO authenticating proxy.  The reason npm works is that we have an exemption for registry.npmjs.org and so proxy authentication is not required for that site.  This was required as npm does not support SPNEGO authentication with proxies.  Essentially the same issue we are having with your binary download from github.com.  Unfortunately exemptions are no longer being granted so github,com requires proxy authentication.  Yes, the OCA was rejected.  I will not bother resubmitting unless this patch has some chance of getting accepted. 

NODE_ORACLEDB_TRACE_INSTALL=TRUE npm install --verbose oracledb@v3.0.1                                                         [37/5850]
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'oracledb@v3.0.1' ]
npm info using npm@6.4.1
npm info using node@v10.13.0
npm verb npm-session 342ebfeaa9e15ccd
npm http fetch GET 304 https://registry.npmjs.org/oracledb 239ms (from cache)
npm timing stage:loadCurrentTree Completed in 360ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
npm timing stage:loadIdealTree Completed in 9ms
npm timing stage:generateActionsToTake Completed in 4ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm timing audit compress Completed in 4ms
npm info audit Submitting payload of 271bytes
npm verb lock using /root/.npm/_locks/staging-bd3355550c5a469e.lock for /app/node_modules/.staging
npm timing action:extract Completed in 68ms
npm timing action:finalize Completed in 3ms
npm timing action:refresh-package-json Completed in 7ms
npm info lifecycle oracledb@3.0.1~preinstall: oracledb@3.0.1
npm timing action:preinstall Completed in 1ms
npm info linkStuff oracledb@3.0.1
npm timing action:build Completed in 1ms
npm info lifecycle oracledb@3.0.1~install: oracledb@3.0.1

> oracledb@3.0.1 install /app/node_modules/oracledb
> node package/oracledbinstall.js

oracledb TRACE In initDynamicProps
oracledb TRACE dynamicProps = { PACKAGE_JSON_VERSION: '3.0.1',
  GITHUB_TAG: 'v3.0.1',
  BINARY_BUILD_NAME: 'oracledb-v3.0.1-node-abi64-linux-x64-oracledb.node',
  PACKAGE_FILE_NAME: 'oracledb-v3.0.1-node-abi64-linux-x64.gz' }
oracledb TRACE In install
oracledb Beginning installation
oracledb TRACE In verifyBinary
oracledb TRACE Checking for binary at /app/node_modules/oracledb/build/Release/oracledb.node
oracledb TRACE In installBinary at: "/app/node_modules/oracledb" mode: 16877
oracledb TRACE In getRemoteFileReadStream github.com /oracle/node-oracledb/releases/download/v3.0.1/oracledb-v3.0.1-node-abi64-linux-x64.gz
oracledb TRACE In getProxyConfig github.com
oracledb TRACE In readProxyUrl
oracledb TRACE In getFileReadStreamByProxy github.com /oracle/node-oracledb/releases/download/v3.0.1/oracledb-v3.0.1-node-abi64-linux-x64.gz our.proxy.com 808
0
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Failed to install binary package oracledb-v3.0.1-node-abi64-linux-x64.gz
oracledb ERR! Error: HTTP proxy request for github.com/oracle/node-oracledb/releases/download/v3.0.1/oracledb-v3.0.1-node-abi64-linux-x64.gz failed with code 407
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm verb lifecycle oracledb@3.0.1~install: unsafe-perm in lifecycle false
npm verb lifecycle oracledb@3.0.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/oracledb/node_modules/.bin:/
app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle oracledb@3.0.1~install: CWD: /app/node_modules/oracledb
npm info lifecycle oracledb@3.0.1~install: Failed to exec install script
npm timing action:install Completed in 115ms

npm verb unlock done using /root/.npm/_locks/staging-bd3355550c5a469e.lock for /app/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 12ms
npm timing stage:runTopLevelLifecycles Completed in 612ms
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

npm verb stack Error: oracledb@3.0.1 install: `node package/oracledbinstall.js`
npm verb stack Exit status 87
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid oracledb@3.0.1
npm verb cwd /app
npm verb Linux 3.10.0-693.11.1.el7.x86_64
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "oracledb@v3.0.1"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@3.0.1 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR! 
npm ERR! Failed at the oracledb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 87, true ]
npm timing audit submit Completed in 559ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 558ms
npm timing audit body Completed in 1ms
npm timing npm Completed in 401175ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-21T15_52_51_212Z-debug.log

**Comment by bmocm** [comment]
Hosting our own binaries also requires hosting a modified version of the npm package as well github,com is hard-coded in oracledbinstall.js.  If I am going to host a modified version of oracledb then I may as well do so with my patch so I do not also need to download and host the binaries.

**Comment by cjbj** [comment]
@bmocm I can see a network exemption would help!

Regarding packaging, see https://oracle.github.io/node-oracledb/INSTALL.html#selfhost for how to host your own binaries - you can easily build a top level package that does not hard code github.com by setting `NODE_ORACLEDB_PACKAGE_HOSTNAME` and `NODE_ORACLEDB_PACKAGE_URL_PATH` at the appropriate time.

Given your company, and that the binaries aren't signed etc, I'm surprised you are not compiling your own.

I'll let you know when I get a review of the external downloader.

**Comment by cjbj** [comment]
Seeing how we have settled on a stable set of platforms and Node.js versions that we build binaries for, and the not-huge size of each binary, I think it might be OK for us to bundle binaries for all platform & Node.js versions into the one package pulled from npm, and make the install script move the appropriate binary to the build/Release directory.  The overall bundle size would be circa 3.5M, and the installed footprint would be smaller than that after the install scripts has pruned unneeded binaries.  This would mean nothing would be needed from GitHub for most users.

**Comment by bmocm** [comment]
Having everything available in a single npm package should solve the download problem for me although I can understand if others would be more sensitive to the download size.  As for hosting binaries we have built ourselves that does not strike me as any more robust from a security standpoint than downloading them from github, assuming that is what you were implying, unless we were to first audit the source code we downloaded from github.  We struggle to keep on top of our own code reviews as it is.  Appreciate you taking the time to look into this whatever course you decide upon.

**Comment by cjbj** [comment]
@dmcghan A more accurate size of the npm package is around 2.6Mb, comprising binaries for 3 OS's for each of 4 Node.js versions.  This will shrink in the periods when only 3 Node.js versions are supported.  And when we swap to N-API we would just need 3 binaries, one per OS.  In the very long term I don't see node-oracledb binaries growing beyond expectations.

**Comment by dmcghan** [comment]
That sounds good to me!

**Comment by cjbj** [comment]
@bmocm See https://github.com/oracle/node-oracledb/issues/1016#issuecomment-445140094 which removes the need for this PR.  You will either (i) only need npm access (ii) be able to internally host the same package used on npmjs.com

**Pull request closed without merging**
