### PR TITLE
Raw type

### PR DESCRIPTION
**Pull request by bjouhier**
This PR adds support for the `RAW` datatype and the `ROWID` pseudo-column.

`RAW` columns are mapped to `Buffer`
`ROWID` is returned as a string

### CODE REVIEW

**Comment by cjbj** [comment]
It's great to see such a comprehensive PR.  Love the tests!  We'll get your [OCA ](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) submission processed and review the PR.

**Comment by bjouhier** [comment]
@cjbj Unfortunately the OCA got stalled by Oracle. I have to get it signed by a VP and I'm procrastinating on this (hate paperwork).

**Comment by cjbj** [comment]
@bjouhier I heard and sympathize.

**Comment by bjouhier** [comment]
@cjbj I tried to merge with latest master and saw that ROWID had been partially implemented by your team. I can resolve the conflicts and resubmit but I'd like to know what your plans are on ROWID. If you finish your implementation (including support for SELECT ROWID ...), I can nuke the ROWID bits from this PR and resubmit only the changes for RAW type.

**Comment by cjbj** [comment]
Hi Bruno,  the general direction is to support ROWID being returned as string instead of Buffer, which was considered. There are some details to be checked regarding UROWID, and with sizes - feel free to help!  Overall it seems better to make this PR just add RAW, and revisit ROWID later.

I pinged our OCA group to make sure they review your paperwork.

**Comment by bjouhier** [comment]
Hi Chris, this PR was actually mapping ROWID to string (and RAW to Buffer) but I wasn't handling all the subtle issues (UROWID for ex) so I'm happy to leave this to you.

I'll trim the PR and resubmit only the RAW support (I should have made 2 separate PRs in the first place).

**Comment by bjouhier** [comment]
@cjbj I've removed the ROWID bits and I've rebased from master (hardest part was the unit tests). Should be ready to go.

**Comment by cjbj** [comment]
Thanks @bjouhier we'll take a look!

**Comment by cjbj** [comment]
RAW support was merged to node-oracledb 1.2.  Thanks @bjouhier

**Pull request closed without merging**
