### PR TITLE
Source code refactor. Abstracted redundant functionalities 

### PR DESCRIPTION
**Pull request by krishnanm86**

### CODE REVIEW

**Comment by krishnanm86** [comment]
Hi, Any news on the status of this pull request.

**Comment by cjbj** [comment]
I heard back from a reviewer.  The changes looks good.  We might make the common method private, or move it into njsUtils so that it can be used across classes.  We'll merge & make this tidy-up after another feature commit lands on the files.  Thanks for submitting the PR.

**Comment by krishnanm86** [comment]
This is great news. I will look forward to the merge. Please get in touch with me if you would also like me to make the method private or introduce it into the njsutils post the merge.

**Comment by cjbj** [comment]
This was merged in 0.4.1.  Thanks for the PR.

**Pull request closed without merging**
