### PR TITLE
WIP: feat: add compatibility with bun

### LINKED ISSUE #1519: Please make node-oracledb compatible with bun
BUN is getting traction and is a fast alternative to node.js and deno. Sadly, when invoked with bun instead of node,  any code using node-oracledb send an exception : NJS-069: node-oracledb 5.5.0 requires Node.js 8.16 or later
Why ? because oracledb.js explicitely reject it. See lines 25-36 in oracledb.js

Please make node-oracledb compatible with BUN

### PR DESCRIPTION
**Pull request by nya1**
Closes #1519 

Changes

1. The preferred way to identify the node version is via `process.versions.node` (same logic is used also [here](https://github.com/oracle/node-oracledb/blob/8388891eb59a13403d607543b578f6e7aa876da8/package/install.js#L79)), there is a fallback to the old `process.version`
2. Binary path location is determined using `path.resolve` in current (node_modules) directory

Bun issues
- [x]  [Event Emitter empty object](https://github.com/oven-sh/bun/issues/1284)
- [x] [Error while attempting to load a module with require as a constant](https://github.com/oven-sh/bun/issues/1831)
- Node extension
  - [x]  [Segmentation fault when trying to call the .node extension](https://github.com/oven-sh/bun/issues/1286)
  - [Missing napi implementation:](https://github.com/oven-sh/bun/issues/158)
    - [ ] `napi_create_external`
    - [ ] `napi_get_value_external`
    - [ ] `napi_make_callback`

### CODE REVIEW

**Comment by cjbj** [comment]
@nya1 this is still marked a WIP.  Shall we merge it into our internal code repo and close this PR (which is our normal release process)?  Or are we waiting for more updates from you?

**Comment by nya1** [comment]
> @nya1 this is still marked a WIP. Shall we merge it into our internal code repo and close this PR (which is our normal release process)? Or are we waiting for more updates from you?

Hello, I've added the draft status on purpose, while working on this issue I discovered some missing napi implementation and bugs in Bun which I reported to the Bun's repository, at the moment there are three major napi implementation missing, I've created a checklist in the PR description (under "Bun issues") with links to Bun's issues to track what we need to have a working/minimum Bun compatibility and go on with the testing and changes.

**Comment by cjbj** [comment]
@nya1 we will wait for you to let us know when you are finished with this PR.

**Comment by Jarred-Sumner** [comment]
`napi_create_external` and `napi_get_value_external` will be available in Bun v0.2.3

**Comment by Jarred-Sumner** [comment]
`napi_make_callback` is implemented in the canary build and `napi_create_external` + `napi_get_value_external` are in  Bun v0.3.0 (there was no v0.2.3)

Assuming there are no bugs (big assumption at the present state), good shot of this working @nya1 

to upgrade:
```bash
bun upgrade --canary
```

**Comment by nya1** [comment]
> `napi_make_callback` is implemented in the canary build and `napi_create_external` + `napi_get_value_external` are in Bun v0.3.0 (there was no v0.2.3)
> 
> Assuming there are no bugs (big assumption at the present state), good shot of this working @nya1
> 
> to upgrade:
> 
> ```shell
> bun upgrade --canary
> ```

Thank you for the update, I've encountered another possible bug while testing, I've created a new issue here: https://github.com/oven-sh/bun/issues/1831

**Comment by cjbj** [comment]
I'm keeping this open so it can be assessed by @nya1 when node-oracledb 6.0 has been released.

**Comment by cjbj** [comment]
@nya1 can you take a look at this PR with node-oracledb 6 and the new pure JS mode?

**Pull request closed without merging**
