### PR TITLE
adds support for pre-compiled binaries

### PR DESCRIPTION
**Pull request by bchr02**
**_sorry had to re-add this pull request to address an issue with my fork which was preventing me from submitting additional pull requests**_
### Using node-pre-gyp and a new bin folder, this pull request adds:
1. **The ability for node-oracledb developers to package binaries, or automate the process of packaging binaries, by performing (or scripting) the following tasks in the following order.**
   1. Install C++ build environment as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   2. Install Node.js as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   3. Install Python 2.7 as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   4. Install the free Oracle Instant Client ZIPs as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   5. `set ORACLE_HOME=C:\oracle\instantclient` for Linux use `export` instead of `set`
   6. `set PATH=%ORACLE_HOME%;%PATH%` for Linux use `export` instead of `set`
   7. `set OCI_LIB_DIR=%ORACLE_HOME%\sdk\lib\msvc` for Linux use `export` instead of `set`
   8. `set OCI_INC_DIR=%ORACLE_HOME%\sdk\include` for Linux use `export` instead of `set`
   9. `git clone https://github.com/bchr02/node-oracledb` then `git checkout prebuild_support`.~~`git clone https://github.com/oracle/node-oracledb` (_or while testing with my repo use_ `git clone https://github.com/bchr02/node-oracledb` then `git checkout prebuild_support`.)~~
   10. cd node-oracledb
   11. `npm install nan`
   12. `npm install node-gyp -g`
   13. `npm install node-pre-gyp -g`
   14. `node-pre-gyp clean`
   15. `node-pre-gyp configure`
   16. `node-pre-gyp build`
   17. `node-pre-gyp package --toolset=oci12.1-msvs2015`
   18. `xcopy build\stage\*.* bin /C /Y` or for Linux: `cp -f build/stage/* bin`
   19. `git add -A`
   20. `git commit`
   21. `git push -u origin master`
2. **The ability for node-oracledb to be installed without the need for a build environment. The following would be a revised list of steps to install node-oracledb once we start including the binaries in the bin folder and a compatible system is used.**
   1. Install Node.js as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   2. Install the free Oracle Instant Client ZIPs as outlined in [INSTALL.md](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
   3. `set ORACLE_HOME=C:\oracle\instantclient` for Linux use `export` instead of `set`
   4. `set PATH=%ORACLE_HOME%;%PATH%` for Linux use `export` instead of `set`
   5. `set OCI_LIB_DIR=%ORACLE_HOME%\sdk\lib\msvc` for Linux use `export` instead of `set`
   6. `set OCI_INC_DIR=%ORACLE_HOME%\sdk\include` for Linux use `export` instead of `set`
3. **The ability for a node-oracledb install to fall back to building when a binary is not found.**
   1. A build environment would be needed otherwise the install would fail.

**IMPORTANT TO UNDERSTAND:** The bin folder is an online only folder. When npm installing node-oracledb the bin folder will not downloaded. Instead, node-pre-gyp will check the **online** github folder for a suitable file. **_Therefore, while testing and locally compiling be sure to remember this and not try to install from a git cloned copy of node-oracledb that you have compiled for.**_

_By the way, you're going to want to reject any of the files within the bin folder. Also, within package.json change the binary.host path so `bchr02` is changed to `oracle` and `prebuild_support` is changes to `master`_

cc: https://github.com/oracle/node-oracledb/issues/18

Signed-off-by: Bill Christo billchristo@gmail.com

### CODE REVIEW

**Comment by pvenkatraman** [comment]
I tried on 2 different windows machines with node 4.4.3 & 5.1.0 and in both I get build errors:

gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs510\node_modules\npm\node_modules\node-gyp\lib\
gure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs510\\node.exe" "C:\\Program Files\\nodejs510\\node_modules\\npm\\node_mo
\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\WORK\github\160419\node-oracledb
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

I tried this on Linux and following the steps able to compile.

Also does node-pre-gyp support node 0.10.x?

**Comment by pvenkatraman** [comment]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

This seem to be error.

**Comment by bchr02** [comment]
Hi @pvenkatraman, Using my ordered list as a guide, do you get this error at item 1 sub section xvi? Also, are you doing a ```git clone https://github.com/bchr02/node-oracledb``` and are you following the instructions as outlined?

In regards to, ```does node-pre-gyp support node 0.10.x?``` I believe it does, but since I have not tested it and since node-pre-gyp's README is not clear I created an issue to confirm. See https://github.com/mapbox/node-pre-gyp/issues/203

**Comment by bchr02** [comment]
I just looked at appveyor.yml with node-pre-gyp and I see testing for nodejs_version: 0.10.36, so it looks like node-pre-gyp does in fact support 0.10.x

**Comment by bchr02** [comment]
@springmeyer just confirmed that node-pre-gyp supports node v0.10.x and greater via https://github.com/mapbox/node-pre-gyp/issues/203#issuecomment-212170189

**Comment by bchr02** [comment]
> gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

>This seem to be error.

@pvenkatraman I just updated step 1 sub section ix within the [instructions](https://github.com/oracle/node-oracledb/pull/392#issue-144078321) so that it is more clear. I crossed out the old wording. I think this is what was causing you the problem. Let me know. Thanks.

**Comment by BuBuaBu** [comment]
Is there any chance to get node-pre-gyp and official pre built binarieis?

**Comment by cjbj** [comment]
For anyone following this PR, we are looking at a lighter weight solution that doesn't have the automatic fallback to compilation if the binary install fails.  See https://github.com/oracle/node-oracledb/issues/18#issuecomment-322675513 and the dev-2.0  branch  [package/README.md](https://github.com/oracle/node-oracledb/blob/dev-2.0/package/README.md) and the dev-2.0 branch [INSTALL.md](https://github.com/oracle/node-oracledb/blob/dev-2.0/INSTALL.md).

If (as I expect) the light weight solution is practical, I'll close out this PR.

**Comment by cjbj** [comment]
@bchr02 I'll close this now we have the lightweight 2.0 binary installer.  Couldn't have done it without you.  Many thanks.

**Pull request closed without merging**
