### PR TITLE
Include Proxy Authorization

### PR DESCRIPTION
**Pull request by rajadurai-mdu31**
extract the auth / user:pass parameter from the url while parsing 
add it as Proxy-Authorization header in the request

Thanks for contributing!

Before submitting PRs for node-oracledb you must have your signed *Oracle Contributor Agreement* accepted.  See https://www.oracle.com/technetwork/community/oca-486395.html

If the problem solved is small, you may find it easier to open an Issue describing the problem and its cause so we can create the fix.

**Note that the ODPI-C submodule does not accept PRs.**  Any required changes to ODPI-C should be submitted in the form of a problem description at https://github.com/oracle/odpi/issues before submitting a node-oracledb PR.

The bottom of your commit message must have the following line using your name and e-mail address as it appears in the OCA Signatories list.

```
Signed-off-by: Your Name <you@example.org>
```

This can be automatically added to pull requests by committing with:

```
git commit --signoff
````

### CODE REVIEW

**Comment by cjbj** [comment]
@rajadurai-mdu31 this would be useful to get merged; have you submitted the [OCA paperwork](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md)?

**Comment by cjbj** [comment]
@rajadurai-mdu31 ping.  Can you submit the [OCA paperwork](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md)?

**Comment by cjbj** [comment]
@rajadurai-mdu31 are you able to sign the OCA?  I'd hate for your submission to be rejected on this technicality.

**Comment by rajadurai-mdu31** [comment]
Sorry for the delay. Have signed the OCA and sent it across.

Let me know the next steps on the sign-off of this change

**Comment by cjbj** [comment]
@rajadurai-mdu31 excellent! 

 Make sure the commit includes `Signed-off-by: Your Name <you@example.org>` 

If you let [me](https://github.com/cjbj) know what email you submitted the OCA paperwork from, I'll get the OCA team to look out specially for it.

**Comment by cjbj** [comment]
@rajadurai-mdu31 thanks.  I've pinged the OCA team to see what they're up to.

**Comment by cjbj** [comment]
@rajadurai-mdu31 I heard our OCA team wanted a change on your OCA form.  Are you able to do that?

**Comment by cjbj** [comment]
@rajadurai-mdu31 ping!

**Comment by cjbj** [comment]
@rajadurai-mdu31 did you get this sorted?

**Comment by cjbj** [comment]
@rajadurai-mdu31 final ping.  Can you sort out the OCA application?

**Comment by cjbj** [comment]
Closing - no activity.

**Pull request closed without merging**
